In [1]:
import numpy as np

## 索引和切片

### 索引

In [20]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr)
print("通过索引获取数据")
print(f"arr[1]:{arr[1]}")
print(f"arr[1][slice(1,2)]:{arr[1][slice(1,4,2)]}")
print(f"arr[(arr>10) & (arr<12)]:{arr[ (arr>10) & (arr<12)]}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
通过索引获取数据
arr[1]:[5 6 7 8]
arr[1][slice(1,2)]:[6 8]
arr[(arr>10) & (arr<12)]:[11]


### 切片

In [22]:
print("通过切片获取数据")
print(f"获取第1行之后的数据:{arr[1:]}")
print(f"获取第3行之前的数据:{arr[:3]}")
print(f"获取最后三个数据:{arr[-3:]}")

print(f"索引和切片的组合:{arr[1,1:3]}")

通过切片获取数据
获取第1行之后的数据:[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
获取第3行之前的数据:[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
获取最后三个数据:[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
索引和切片的组合:[6 7]
