In [1]:
import numpy as np

## 数组的创建

### 基础的创建方法

In [2]:

print("-----基础的创建方法-----")
arr = np.array([
    [1,2,3],
    [4,5,6]
],dtype='int8')
print(f"arr的形状 {arr.shape}")
print(f"arr的dtype {arr.dtype}")
print(f"arr的纬度 {arr.ndim}")

### 通过copy来创建
print("-----通过copy来创建-----")
arr_copy = arr.copy()
print("改变copy数组的值")
arr_copy = np.array([1,2,3])
print(f"arr的形状 {arr_copy.shape}")
print(f"arr的dtype {arr_copy.dtype}")
print(f"arr的纬度 {arr_copy.ndim}")

-----基础的创建方法-----
arr的形状 (2, 3)
arr的dtype int8
arr的纬度 2
-----通过copy来创建-----
改变copy数组的值
arr的形状 (3,)
arr的dtype int64
arr的纬度 1


### 预定义形状

In [8]:
print("-----预定义形状-----")
arr_zeros = np.zeros((2,3),dtype='int8')
print(f"arr_zeros: {arr_zeros}")
arr_empty = np.empty((2,3))
print(f"arr_empty: {arr_empty}")
arr_full = np.full((2,3),1)
print(f"arr_full: {arr_full}")
arr_ones_like = np.ones_like(arr)
print(f"arr_ones_like: {arr_ones_like}")
arr_full_like = np.full_like(arr,2)
print(f"arr_full_like: {arr_full_like}")

-----预定义形状-----
arr_zeros: [[0 0 0]
 [0 0 0]]
arr_empty: [[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]
arr_full: [[1 1 1]
 [1 1 1]]
arr_ones_like: [[1 1 1]
 [1 1 1]]
arr_full_like: [[2 2 2]
 [2 2 2]]
