In [1]:
import numpy as np

## 算数运算

In [4]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.copy(arr1)

print(f"加法,{arr1 + arr2}")
print(f"减法,{arr1 - arr2}")
print(f"除法,{arr1 / arr2}")
print(f"乘法,{arr1 * arr2}")
print(f"取整,{arr1 ** arr2}")

加法,[[ 2  4  6]
 [ 8 10 12]]
减法,[[0 0 0]
 [0 0 0]]
除法,[[1. 1. 1.]
 [1. 1. 1.]]
乘法,[[ 1  4  9]
 [16 25 36]]
取整,[[    1     4    27]
 [  256  3125 46656]]


### 形状不同的矩阵运算

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4], [5], [6]])
print(arr1.shape, arr2.shape)

print(f"加法,{arr1 + arr2}")
print(f"减法,{arr1 - arr2}")
print(f"乘法,{arr1 * arr2}")
print(f"取整,{arr1 ** arr2}")


(3,) (3, 1)
加法,[[5 6 7]
 [6 7 8]
 [7 8 9]]
减法,[[-3 -2 -1]
 [-4 -3 -2]
 [-5 -4 -3]]
乘法,[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
取整,[[  1  16  81]
 [  1  32 243]
 [  1  64 729]]


### 矩阵的运算

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(f"向量的点积, {np.dot(a,b)}")

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 2, 3], [4, 5, 6]])
print(A.shape,B.T.shape)
print(f"矩阵的乘法, {A @ B.T}")


向量的点积, 32
(3, 3) (3, 2)
矩阵的乘法, [[ 14  32]
 [ 32  77]
 [ 50 122]]
