# 数组的基本使用

In [1]:
import numpy as np

In [2]:
arr0 = np.array(1)
print(arr0)

1


In [3]:
arr1 = np.array([1,3,4])
print(arr1)
print(f"数据的维度:{arr1.ndim}")

[1 3 4]
数据的维度:1


In [6]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)
print(f"数据的维度:{arr2.ndim}")

[[1 2 3]
 [4 5 6]]
数据的维度:2


# 数组的同质性 隐式转换

In [ ]:
arr3 = np.array([1,'hello']) #1 隐式转换为了 字符串'1'
print(arr3)

['1' 'hello']


# 数组的属性

In [16]:
arr4 = np.array([[1,2,3], [4,5,6]])
print(f"数组的维度:{arr4.ndim}")
print(f"数组的形状:{arr4.shape}")
print(f"数组的元素个数:{arr4.size}")
print(f"数组的数据类型:{arr4.dtype}")
print(f"数组的转置:{arr4.T}")

数组的维度:2
数组的形状:(2, 3)
数组的元素个数:6
数组的数据类型:int64
数组的转置:[[1 4]
 [2 5]
 [3 6]]


# 数组的创建

## 数组基础的创建

In [18]:
# 通过list进行创建
arr = np.array([1,2,3])
print(arr)

# copy来创建
arr_copy = np.copy(arr)
print(arr_copy)

#预定义形状

[1 2 3]
[1 2 3]
